export type UiLanguage = 'zh-CN' | 'zh-TW' | 'en' | 'ja';

const zhCN = {
  loading: '设置加载中...',
  general: '通用',
  generalDescription: '应用界面、网络、日志与维护',
  interfaceAndStartup: '界面与启动',
  interfaceAndStartupDescription: '应用外观与系统启动行为',
  interface: '界面',
  interfaceLanguage: '界面语言',
  interfaceLanguageDescription: '当前版本完整支持中文简体',
  theme: '主题',
  themeDescription: '选择应用的外观主题',
  followSystem: '跟随系统',
  light: '浅色',
  dark: '深色',
  startOnBoot: '开机自启',
  startOnBootDescription: '系统启动时自动运行 SnapLingo',
  network: '网络',
  networkDescription: '代理、超时与失败重试策略',
  connection: '连接',
  proxy: '代理设置',
  proxyDescription: '应用于翻译、OCR 和自定义服务请求',
  noProxy: '不使用代理',
  manualProxy: '手动代理',
  proxyAddress: '代理地址',
  proxyAddressDescription: '支持 HTTP、HTTPS 或 SOCKS5 地址',
  requestTimeout: '请求超时时间',
  requestTimeoutDescription: '单次网络请求的最长等待时间',
  retryCount: '失败重试次数',
  retryCountDescription: '仅重试网络错误和服务端 5xx 错误',
  logsAndMaintenance: '日志与维护',
  logsAndMaintenanceDescription: '日志记录和本地数据维护工具',
  logs: '日志',
  logLevel: '日志级别',
  logLevelDescription: '仅保存此级别及以上的应用日志',
  logRetentionDays: '日志保留天数',
  logRetentionDaysDescription: '每天 08:00 自动删除更早的日志',
  days: '天',
  logStorage: '日志存储',
  logStorageDescription: '日志保存在本地 SQLite 的 app_logs 表中',
  recentLogs: '最近 {count} 条',
  logActions: '日志操作',
  refreshLogs: '刷新日志',
  clearLogs: '清空日志',
  clearLogsConfirm: '确定要清空所有应用日志吗？',
  dataMaintenance: '数据维护',
  historyRecords: '历史记录',
  clearHistoryConfirm: '确定要清空全部翻译和 OCR 历史吗？独立收藏不会被删除。',
  clearAllHistory: '清除所有历史记录',
  appSettings: '应用设置',
  resetSettingsDescription: '恢复为首次安装时的默认设置',
  unavailable: '暂未开放',
  experimental: '实验性功能',
  experimentalDescription: '尚在验证中的性能功能',
  performance: '性能',
  gpuComposition: 'GPU 合成',
  gpuCompositionDescription: '为截图画布启用实验性的 GPU 合成提示',
  performanceMonitoring: '性能监控',
  performanceMonitoringDescription: '记录截图工作流耗时，便于在日志中分析',
  about: '关于',
  aboutDescription: '版本、开源协议与更新',
  currentVersion: '当前版本',
  openSourceLicense: '开源协议',
  softwareUpdate: '软件更新',
  reading: '读取中…',
  unknown: '未知',
  autoSave: '自动保存',
  settings: '设置',
  library: '资料库',
  screenshot: '截图',
  translation: '翻译',
  ocr: 'OCR',
  services: '服务',
  favorites: '收藏夹',
  history: '历史记录',
  historyAndFavorites: '历史与收藏',
  configure: '设置',
  retentionDays: '保留天数',
  historyUsed: '历史已用',
  favoritesUsed: '收藏已用',
  capacityDescription: '统一管理自动清理和资料库容量',
  close: '关闭',
  autoCleanupHistory: '自动清理历史记录',
  autoCleanupHistoryDescription: '删除超过保留天数的非收藏记录',
  historyRetentionDays: '历史记录保留天数',
  historyRetentionDaysDescription: '超过此天数的历史记录将被自动删除',
  maximumRecords: '最多保留记录数',
  maximumRecordsDescription: '收藏记录不计入自动清理上限',
  favoritesCapacity: '收藏夹容量',
  favoritesCapacityDescription: '达到上限后停止新增，不会自动删除收藏',
  capacityNotice: '收藏是用户主动保存的内容。容量不足时会提示先整理收藏，避免静默删除重要资料。',
  cancel: '取消',
  saveSettings: '保存设置',
} as const;

type UiTextKey = keyof typeof zhCN;
type UiDictionary = Record<UiTextKey, string>;

const dictionaries: Record<Exclude<UiLanguage, 'zh-CN'>, UiDictionary> = {
  'zh-TW': {
    ...zhCN,
    loading: '設定載入中...', general: '一般', generalDescription: '應用程式介面、網路、日誌與維護',
    interfaceAndStartup: '介面與啟動', interfaceAndStartupDescription: '應用程式外觀與系統啟動行為', interface: '介面',
    interfaceLanguage: '介面語言', interfaceLanguageDescription: '選擇應用程式顯示語言', theme: '主題', themeDescription: '選擇應用程式外觀主題',
    followSystem: '跟隨系統', light: '淺色', dark: '深色', startOnBoot: '開機自動啟動', startOnBootDescription: '系統啟動時自動執行 SnapLingo',
    network: '網路', networkDescription: '代理、逾時與失敗重試策略', connection: '連線', proxy: '代理設定', proxyDescription: '套用於翻譯、OCR 與自訂服務請求',
    noProxy: '不使用代理', manualProxy: '手動代理', proxyAddress: '代理位址', proxyAddressDescription: '支援 HTTP、HTTPS 或 SOCKS5 位址',
    requestTimeout: '請求逾時時間', requestTimeoutDescription: '單次網路請求的最長等待時間', retryCount: '失敗重試次數', retryCountDescription: '僅重試網路錯誤與伺服器 5xx 錯誤',
    logsAndMaintenance: '日誌與維護', logsAndMaintenanceDescription: '日誌記錄與本機資料維護工具', logs: '日誌', logLevel: '日誌層級', logLevelDescription: '僅儲存此層級及以上的應用程式日誌',
    logRetentionDays: '日誌保留天數', logRetentionDaysDescription: '每天 08:00 自動刪除更早的日誌', days: '天', logStorage: '日誌儲存',
    logStorageDescription: '日誌儲存在本機 SQLite 的 app_logs 資料表', recentLogs: '最近 {count} 筆', logActions: '日誌操作', refreshLogs: '重新整理日誌', clearLogs: '清空日誌', clearLogsConfirm: '確定要清空所有應用程式日誌嗎？',
    dataMaintenance: '資料維護', historyRecords: '歷史記錄', clearHistoryConfirm: '確定要清空全部翻譯與 OCR 歷史嗎？獨立收藏不會被刪除。', clearAllHistory: '清除所有歷史記錄', appSettings: '應用程式設定', resetSettingsDescription: '恢復為首次安裝時的預設設定', unavailable: '尚未開放',
    experimental: '實驗性功能', experimentalDescription: '仍在驗證中的效能功能', performance: '效能', gpuComposition: 'GPU 合成', gpuCompositionDescription: '為截圖畫布啟用實驗性的 GPU 合成提示', performanceMonitoring: '效能監控', performanceMonitoringDescription: '記錄截圖工作流程耗時，以便在日誌中分析',
    about: '關於', aboutDescription: '版本、開源授權與更新', currentVersion: '目前版本', openSourceLicense: '開源授權', softwareUpdate: '軟體更新', reading: '讀取中…', unknown: '未知', autoSave: '自動儲存',
    settings: '設定', library: '資料庫', screenshot: '截圖', translation: '翻譯', ocr: 'OCR', services: '服務', favorites: '收藏夾', history: '歷史記錄', historyAndFavorites: '歷史與收藏', configure: '設定', retentionDays: '保留天數', historyUsed: '歷史已用', favoritesUsed: '收藏已用', capacityDescription: '統一管理自動清理與資料庫容量', close: '關閉',
    autoCleanupHistory: '自動清理歷史記錄', autoCleanupHistoryDescription: '刪除超過保留天數的非收藏記錄', historyRetentionDays: '歷史記錄保留天數', historyRetentionDaysDescription: '超過此天數的歷史記錄將被自動刪除', maximumRecords: '最多保留記錄數', maximumRecordsDescription: '收藏記錄不計入自動清理上限', favoritesCapacity: '收藏夾容量', favoritesCapacityDescription: '達到上限後停止新增，不會自動刪除收藏', capacityNotice: '收藏是使用者主動儲存的內容。容量不足時會提示先整理收藏，避免靜默刪除重要資料。', cancel: '取消', saveSettings: '儲存設定',
  },
  en: {
    loading: 'Loading settings...', general: 'General', generalDescription: 'Interface, network, logs, and maintenance',
    interfaceAndStartup: 'Interface & startup', interfaceAndStartupDescription: 'Appearance and system startup behavior', interface: 'Interface', interfaceLanguage: 'Language', interfaceLanguageDescription: 'Choose the application display language', theme: 'Theme', themeDescription: 'Choose the application appearance', followSystem: 'Follow system', light: 'Light', dark: 'Dark', startOnBoot: 'Launch at startup', startOnBootDescription: 'Run SnapLingo automatically when the system starts',
    network: 'Network', networkDescription: 'Proxy, timeout, and retry policy', connection: 'Connection', proxy: 'Proxy', proxyDescription: 'Used for translation, OCR, and custom service requests', noProxy: 'No proxy', manualProxy: 'Manual proxy', proxyAddress: 'Proxy address', proxyAddressDescription: 'Supports HTTP, HTTPS, and SOCKS5 addresses', requestTimeout: 'Request timeout', requestTimeoutDescription: 'Maximum wait time for a network request', retryCount: 'Retry count', retryCountDescription: 'Only retries network errors and server 5xx responses',
    logsAndMaintenance: 'Logs & maintenance', logsAndMaintenanceDescription: 'Application logs and local data maintenance', logs: 'Logs', logLevel: 'Log level', logLevelDescription: 'Only store logs at this level or higher', logRetentionDays: 'Log retention', logRetentionDaysDescription: 'Automatically delete older logs every day at 08:00', days: 'days', logStorage: 'Log storage', logStorageDescription: 'Logs are stored in the local SQLite app_logs table', recentLogs: '{count} recent entries', logActions: 'Log actions', refreshLogs: 'Refresh logs', clearLogs: 'Clear logs', clearLogsConfirm: 'Clear all application logs?',
    dataMaintenance: 'Data maintenance', historyRecords: 'History', clearHistoryConfirm: 'Clear all translation and OCR history? Separate favorites will not be deleted.', clearAllHistory: 'Clear all history', appSettings: 'Application settings', resetSettingsDescription: 'Restore the default settings from first installation', unavailable: 'Not available yet',
    experimental: 'Experimental', experimentalDescription: 'Performance features still under evaluation', performance: 'Performance', gpuComposition: 'GPU compositing', gpuCompositionDescription: 'Enable experimental GPU compositing hints for the capture canvas', performanceMonitoring: 'Performance monitoring', performanceMonitoringDescription: 'Record capture workflow timings for log analysis',
    about: 'About', aboutDescription: 'Version, open-source license, and updates', currentVersion: 'Current version', openSourceLicense: 'Open-source license', softwareUpdate: 'Software update', reading: 'Loading…', unknown: 'Unknown', autoSave: 'Auto-save',
    settings: 'Settings', library: 'Library', screenshot: 'Capture', translation: 'Translation', ocr: 'OCR', services: 'Services', favorites: 'Favorites', history: 'History', historyAndFavorites: 'History & favorites', configure: 'Configure', retentionDays: 'Retention', historyUsed: 'History used', favoritesUsed: 'Favorites used', capacityDescription: 'Manage automatic cleanup and library capacity', close: 'Close',
    autoCleanupHistory: 'Automatically clean history', autoCleanupHistoryDescription: 'Delete non-favorite records older than the retention period', historyRetentionDays: 'History retention', historyRetentionDaysDescription: 'History older than this will be deleted automatically', maximumRecords: 'Maximum history records', maximumRecordsDescription: 'Favorite records do not count toward the cleanup limit', favoritesCapacity: 'Favorites capacity', favoritesCapacityDescription: 'Stop adding at the limit; existing favorites are never deleted automatically', capacityNotice: 'Favorites are saved intentionally. When capacity is full, SnapLingo asks you to organize them instead of silently deleting important content.', cancel: 'Cancel', saveSettings: 'Save settings',
  },
  ja: {
    loading: '設定を読み込み中...', general: '一般', generalDescription: 'インターフェース、ネットワーク、ログ、メンテナンス',
    interfaceAndStartup: '表示と起動', interfaceAndStartupDescription: '外観とシステム起動時の動作', interface: 'インターフェース', interfaceLanguage: '表示言語', interfaceLanguageDescription: 'アプリの表示言語を選択します', theme: 'テーマ', themeDescription: 'アプリの外観を選択します', followSystem: 'システムに従う', light: 'ライト', dark: 'ダーク', startOnBoot: '自動起動', startOnBootDescription: 'システム起動時に SnapLingo を自動実行します',
    network: 'ネットワーク', networkDescription: 'プロキシ、タイムアウト、再試行ポリシー', connection: '接続', proxy: 'プロキシ設定', proxyDescription: '翻訳、OCR、カスタムサービスのリクエストに適用します', noProxy: 'プロキシを使用しない', manualProxy: '手動プロキシ', proxyAddress: 'プロキシアドレス', proxyAddressDescription: 'HTTP、HTTPS、SOCKS5 に対応します', requestTimeout: 'リクエストタイムアウト', requestTimeoutDescription: '1 回のネットワークリクエストの最大待機時間', retryCount: '再試行回数', retryCountDescription: 'ネットワークエラーとサーバーの 5xx エラーのみ再試行します',
    logsAndMaintenance: 'ログとメンテナンス', logsAndMaintenanceDescription: 'アプリログとローカルデータのメンテナンス', logs: 'ログ', logLevel: 'ログレベル', logLevelDescription: 'このレベル以上のログのみ保存します', logRetentionDays: 'ログ保持日数', logRetentionDaysDescription: '毎日 08:00 に古いログを自動削除します', days: '日', logStorage: 'ログ保存先', logStorageDescription: 'ログはローカル SQLite の app_logs テーブルに保存されます', recentLogs: '最近 {count} 件', logActions: 'ログ操作', refreshLogs: 'ログを更新', clearLogs: 'ログを消去', clearLogsConfirm: 'すべてのアプリログを消去しますか？',
    dataMaintenance: 'データメンテナンス', historyRecords: '履歴', clearHistoryConfirm: '翻訳と OCR の履歴をすべて消去しますか？独立したお気に入りは削除されません。', clearAllHistory: 'すべての履歴を消去', appSettings: 'アプリ設定', resetSettingsDescription: '初回インストール時の既定設定に戻します', unavailable: '未対応',
    experimental: '試験的機能', experimentalDescription: '検証中のパフォーマンス機能', performance: 'パフォーマンス', gpuComposition: 'GPU 合成', gpuCompositionDescription: 'キャプチャキャンバスで試験的な GPU 合成ヒントを有効にします', performanceMonitoring: 'パフォーマンス監視', performanceMonitoringDescription: 'キャプチャ処理時間をログに記録して分析します',
    about: 'このアプリについて', aboutDescription: 'バージョン、オープンソースライセンス、更新', currentVersion: '現在のバージョン', openSourceLicense: 'オープンソースライセンス', softwareUpdate: 'ソフトウェア更新', reading: '読み込み中…', unknown: '不明', autoSave: '自動保存',
    settings: '設定', library: 'ライブラリ', screenshot: 'キャプチャ', translation: '翻訳', ocr: 'OCR', services: 'サービス', favorites: 'お気に入り', history: '履歴', historyAndFavorites: '履歴とお気に入り', configure: '設定', retentionDays: '保持日数', historyUsed: '履歴の使用数', favoritesUsed: 'お気に入りの使用数', capacityDescription: '自動クリーンアップとライブラリ容量を管理します', close: '閉じる',
    autoCleanupHistory: '履歴を自動整理', autoCleanupHistoryDescription: '保持期間を超えたお気に入り以外の履歴を削除します', historyRetentionDays: '履歴保持日数', historyRetentionDaysDescription: 'この日数を超えた履歴は自動的に削除されます', maximumRecords: '履歴の最大件数', maximumRecordsDescription: 'お気に入りは自動整理の上限に含まれません', favoritesCapacity: 'お気に入り容量', favoritesCapacityDescription: '上限に達すると追加を停止し、既存のお気に入りは自動削除しません', capacityNotice: 'お気に入りはユーザーが明示的に保存した内容です。容量不足時は重要な内容を無断で削除せず、整理を促します。', cancel: 'キャンセル', saveSettings: '設定を保存',
  },
};

export function uiText(language: string | undefined, key: UiTextKey): string {
  if (language === 'zh-CN' || !language) return zhCN[key];
  return dictionaries[language as Exclude<UiLanguage, 'zh-CN'>]?.[key] ?? zhCN[key];
}
